project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "Lyon Presentations"
  favicon: images/logo_lyon.png
  repo-url: https://github.com/njlyon0/lyon_talks
  repo-actions: [issue]
  navbar:
    right:
      - text: "Profile"
        href: https://njlyon0.github.io/
      - icon: github
        href: https://github.com/njlyon0/lyon_talks
        aria-label: GitHub
  sidebar:
    style: docked
    collapse-level: 2
    contents:
      - text: "Home"
        href: index.qmd
      - section: "2022-20xx"
        contents:
          - text: "LTER Talks"
            href: lter.qmd
  page-footer:
    center: "Copyright &copy; 2026, Nicholas J Lyon"

execute:
  freeze: auto

format:
  html:
    code-overflow: wrap
    code-line-numbers: false
    code-copy: hover
    theme:
      light: lyonlight.scss
      dark: lyondark.scss
    mainfont: Open Sans
    toc: true
    link-external-newwindow: true
    link-external-icon: false
